export const ADD_TO_CART = 'ADD_TO_CART';
export const SHOW_CART = 'SHOW_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const MODIFY_CART = 'MODIFY_CART';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';